// List of countries for dropdown selection
export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: 'US', name: 'United States' },
  { code: 'CA', name: 'Canada' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'AU', name: 'Australia' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'IT', name: 'Italy' },
  { code: 'ES', name: 'Spain' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'BE', name: 'Belgium' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'AT', name: 'Austria' },
  { code: 'SE', name: 'Sweden' },
  { code: 'NO', name: 'Norway' },
  { code: 'DK', name: 'Denmark' },
  { code: 'FI', name: 'Finland' },
  { code: 'PL', name: 'Poland' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'IE', name: 'Ireland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'GR', name: 'Greece' },
  { code: 'TR', name: 'Turkey' },
  { code: 'JP', name: 'Japan' },
  { code: 'CN', name: 'China' },
  { code: 'IN', name: 'India' },
  { code: 'KR', name: 'South Korea' },
  { code: 'SG', name: 'Singapore' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'TH', name: 'Thailand' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'PH', name: 'Philippines' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'EG', name: 'Egypt' },
  { code: 'KE', name: 'Kenya' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'BR', name: 'Brazil' },
  { code: 'MX', name: 'Mexico' },
  { code: 'AR', name: 'Argentina' },
  { code: 'CL', name: 'Chile' },
  { code: 'CO', name: 'Colombia' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Israel', code: 'IL' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Oman', code: 'OM' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Iran', code: 'IR' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Russia', code: 'RU' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Romania', code: 'RO' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'Malta', code: 'MT' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Panama', code: 'PA' },
  { name: 'Costa Rica', code: 'CR' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Honduras', code: 'HN' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Libya', code: 'LY' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Angola', code: 'AO' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Laos', code: 'LA' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Moldova', code: 'MD' },
  { name: 'Albania', code: 'AL' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'North Macedonia', code: 'MK' },
  { name: 'Montenegro', code: 'ME' },
  { name: 'Kosovo', code: 'XK' },
].sort((a, b) => a.name.localeCompare(b.name));

export const getCountryByName = (name: string): Country | undefined => {
  return COUNTRIES.find(c => c.name.toLowerCase() === name.toLowerCase());
};

export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find(c => c.code.toLowerCase() === code.toLowerCase());
};

